[env:nano]
platform = atmelavr
framework = arduino
board = nanoatmega328new
upload_protocol = arduino
upload_port = COM1

[env:leonardo]
platform = atmelavr
framework = arduino
board = leonardo
upload_protocol = avr109
